[package]
name = "pb-ui"
version = "0.1.0"
authors = ["Andrew Hickman <me@andrewhickman.dev>"]
publish = false
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", default-features = false }
pb-engine = { path = "../pb-engine" }
pb-render = { path = "../pb-render" }
