[package]
name = "pb-engine"
version = "0.1.0"
authors = ["Andrew Hickman <me@andrewhickman.dev>"]
publish = false
edition = "2021"

[features]
dev = ["avian2d/debug-plugin", "vleue_navigator/debug-with-gizmos"]

[dependencies]
anyhow = "1.0.86"
avian2d = { version = "0.2.1", default-features = false, features = ["2d", "f32", "parry-f32", "parallel", "bevy_scene"] }
bevy = { version = "0.15.0", default-features = false, features = ["bevy_state", "bevy_scene", "bevy_render"] }
pb-util = { version = "0.1.0", path = "../pb-util" }
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.44.1", features = ["sync"] }
vleue_navigator = { version = "0.11.1", features = ["avian2d", "tracing"], default-features = false }
