[package]
name = "pb-engine"
version = "0.1.0"
authors = ["Andrew Hickman <me@andrewhickman.dev>"]
publish = false
edition = "2021"

[features]
dev = ["bevy_rapier2d/debug-render-2d"]

[dependencies]
bevy = { version = "0.14.0-rc.2", default-features = false, features = ["bevy_render", "bevy_state"] }
bevy_rapier2d = { git = "https://github.com/dimforge/bevy_rapier.git", default-features = false, features = ["dim2"] }
serde = { version = "1.0.203", features = ["derive"] }
