[package]
name = "pb-engine"
version = "0.1.0"
authors = ["Andrew Hickman <me@andrewhickman.dev>"]
publish = false
edition = "2021"

[features]
dev = ["bevy_rapier2d/debug-render-2d"]

[dependencies]
anyhow = "1.0.86"
bevy = { version = "0.15.0", default-features = false, features = ["bevy_render", "bevy_state", "bevy_scene"] }
bevy_rapier2d = { version = "0.28.0", default-features = false, features = ["dim2"] }
serde = { version = "1.0.203", features = ["derive"] }
