[package]
name = "pb-model"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[build-dependencies]
prost = "0.13.5"
prost-build = "0.13.5"
protox = "0.8.0"

[dependencies]
prost = "0.13.5"
prost-reflect = { version = "0.15.0", features = ["serde"] }
serde_json = "1.0.140"
