[package]
name = "pb-learn"
version = "0.1.0"
authors = ["Andrew Hickman <me@andrewhickman.dev>"]
publish = false
edition = "2021"

[dependencies]
approx = "0.5.1"
avian2d = { version = "0.2.1", default-features = false }
bevy = { version = "0.15.3", default-features = false }
burn = { version = "0.16.0", features = ["autodiff", "wgpu"] }
clap = { version = "4.5.34", features = ["derive"] }
glam = { version = "0.29.2", default-features = false, features = ["rand"] }
pb-engine = { version = "0.1.0", path = "../pb-engine" }
rand = "0.9.0"
rand_distr = "0.5.1"

# https://github.com/tracel-ai/burn/issues/2876
bincode = "=2.0.0-rc.3"
bincode_derive = "=2.0.0-rc.3"
