[package]
name = "pb-learn"
version = "0.1.0"
authors = ["Andrew Hickman <me@andrewhickman.dev>"]
publish = false
edition = "2021"

[lib]
name = "pb_learn"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
